In [21]:
!pip install -U scikit-learn

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.13/dist-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (2.1.3)
Requirement already satisfied: scipy>=1.10.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (2.25.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)

In [22]:
import sklearn
print("Scikit-learn version:", sklearn.__version__)

Scikit-learn version: 1.9.0

In [23]:
df = pd.read_csv('car-details.csv')
df.sample(5)

,name,company,model,edition,year,owner,fuel,seller_type,transmission,km_driven,mileage_mpg,engine_cc,max_power_bhp,torque_nm,seats,selling_price
2739,Hyundai EON Magna Plus,Hyundai,EON,Magna Plus,2012,First,Petrol,Individual,Manual,56000,49.60,814.0,55.20,74.50,5.0,180000
976,Hyundai Xcent 1.2 Kappa S Option,Hyundai,Xcent,1.2 Kappa S Option,2014,Second,Petrol,Individual,Manual,46000,44.88,1197.0,81.86,113.75,5.0,450000
2631,Maruti Swift Dzire AMT VXI,Maruti,Swift,Dzire AMT VXI,2018,First,Petrol,Individual,Automatic,28000,49.84,1197.0,81.80,113.00,5.0,680000
3184,Maruti Alto LX,Maruti,Alto,LX,2006,Second,Petrol,Individual,Manual,100000,46.28,796.0,46.30,62.00,5.0,120000
6708,Hyundai i20 Active 1.4 SX,Hyundai,i20,Active 1.4 SX,2016,Second,Diesel,Individual,Manual,111000,49.78,1396.0,88.73,220.00,5.0,700000

In [24]:
df.info() #Checking info about the data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6926 entries, 0 to 6925
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           6926 non-null   object
 1   company        6926 non-null   object
 2   model          6926 non-null   object
 3   edition        6926 non-null   object
 4   year           6926 non-null   int64
 5   owner          6926 non-null   object
 6   fuel           6926 non-null   object
 7   seller_type    6926 non-null   object
 8   transmission   6926 non-null   object
 9   km_driven      6926 non-null   int64
 10  mileage_mpg    6718 non-null   float64
 11  engine_cc      6718 non-null   float64
 12  max_power_bhp  6717 non-null   float64
 13  torque_nm      6717 non-null   float64
 14  seats          6718 non-null   float64
 15  selling_price  6926 non-null   int64
dtypes: float64(5), int64(3), object(8)
memory usage: 865.9+ KB

In [25]:
df.isna().sum() # Chcking for null values

name               0
company            0
model              0
edition            0
year               0
owner              0
fuel               0
seller_type        0
transmission       0
km_driven          0
mileage_mpg      208
engine_cc        208
max_power_bhp    209
torque_nm        209
seats            208
selling_price      0
dtype: int64

In [26]:
df.shape

(6926, 16)

In [27]:
for col in df.select_dtypes(include='object').columns: # Selects all the categorical columns
  print(f"Column: {col}")                         # Prints column name
  print(f"Cardinality: {df[col].nunique()}")      # Prints number of unique values of that column
  print(df[col].unique())
  print(df[col].value_counts(normalize=True))
  print()

Column: name
Cardinality: 2058
['Maruti Swift Dzire VDI' 'Skoda Rapid 1.5 TDI Ambition'
 'Honda City 2017-2020 EXi' ... 'Tata Nexon 1.5 Revotorq XT'
 'Ford Freestyle Titanium Plus Diesel BSIV'
 'Toyota Innova 2.5 GX (Diesel) 8 Seater BS IV']
name
Maruti Swift Dzire VDI                          0.017037
Maruti Alto 800 LXI                             0.010973
Maruti Alto LXi                                 0.009962
Maruti Swift VDI                                0.008663
Maruti Swift VDI BSIV                           0.008085
                                                  ...
Ford EcoSport 1.5 TDCi Titanium Plus BE BSIV    0.000144
Ford Figo 1.5 Sports Edition MT                 0.000144
Volkswagen Polo Select 1.2 MPI Highline         0.000144
Honda Jazz V Diesel                             0.000144
Renault Duster RXZ 110PS AMT BSIV               0.000144
Name: proportion, Length: 2058, dtype: float64

Column: company
Cardinality: 32
['Maruti' 'Skoda' 'Honda' 'Hyundai' 'Toyota' 'Ford' 'Renault' 'Mahindra'
 'Tata' 'Chevrolet' 'Fiat' 'Datsun' 'Jeep' 'Mercedes-Benz' 'Mitsubishi'
 'Audi' 'Volkswagen' 'BMW' 'Nissan' 'Lexus' 'Jaguar' 'Land' 'MG' 'Volvo'
 'Daewoo' 'Kia' 'Force' 'Ambassador' 'Ashok' 'Isuzu' 'Opel' 'Peugeot']
company
Maruti           0.312590
Hyundai          0.182934
Mahindra         0.104389
Tata             0.093416
Honda            0.052267
Ford             0.052122
Toyota           0.051545
Chevrolet        0.031187
Renault          0.029743
Volkswagen       0.025123
Nissan           0.010540
Skoda            0.010107
Datsun           0.008230
BMW              0.006786
Mercedes-Benz    0.006642
Fiat             0.006353
Audi             0.004765
Jeep             0.003176
Mitsubishi       0.001588
Volvo            0.001299
Jaguar           0.001155
Isuzu            0.000578
Force            0.000578
Ambassador       0.000578
Daewoo           0.000433
MG               0.000433
Land             0.000433
Kia              0.000433
Lexus            0.000144
Ashok            0.000144
Opel             0.000144
Peugeot          0.000144
Name: proportion, dtype: float64

Column: model
Cardinality: 207
['Swift' 'Rapid' 'City' 'i20' 'Xcent' 'Wagon' '800' 'Etios' 'Figo'
 'Duster' 'Zen' 'KUV' 'Ertiga' 'Alto' 'Verito' 'WR-V' 'SX4' 'Tigor'
 'Baleno' 'Enjoy' 'Omni' 'Vitara' 'Palio' 'Verna' 'GO' 'Safari' 'Compass'
 'Fortuner' 'Innova' 'B' 'Amaze' 'Pajero' 'Ciaz' 'Jazz' 'A6' 'Corolla'
 'New' 'Manza' 'i10' 'Ameo' 'Indica' 'Vento' 'EcoSport' 'X1' 'Celerio'
 'Polo' 'Eeco' 'Scorpio' 'Freestyle' 'Passat' 'XUV500' 'Indigo' 'Terrano'
 'Creta' 'KWID' 'Santro' 'Q5' 'ES' 'XF' 'Wrangler' 'Rover' 'S-Class' '5'
 'X4' 'Superb' 'E-Class' 'Hector' 'XC40' 'Q7' 'Elantra' 'XE' 'Nexon' 'CLA'
 'Glanza' '3' 'Camry' 'XC90' 'Ritz' 'Grand' 'Matiz' 'Zest' 'Getz' 'Elite'
 'Brio' 'Hexa' 'Sunny' 'Micra' 'Ssangyong' 'Quanto' 'Accent' 'Ignis'
 'Marazzo' 'Tiago' 'Thar' 'Sumo' 'Bolero' 'GL-Class' 'Beat' 'Willys'
 'A-Star' 'XUV300' 'Nano' 'GTI' 'V40' 'CR-V' 'EON' 'RediGO' 'Captiva'
 'Fiesta' 'Seltos' 'Civic' 'Sail' 'Venture' 'Estilo' 'Classic' 'BR-V'
 'Ecosport' 'Aria' 'TUV' 'Bolt' 'Accord' 'Xylo' 'Grande' 'S-Cross' 'Yaris'
 'Tavera' 'Linea' 'Endeavour' 'Aveo' 'Esteem' 'Triber' 'Fusion' 'Octavia'
 'A4' 'XL6' 'Santa' 'Spark' 'Aspire' 'Punto' 'Optra' 'Mobilio' 'Qualis'
 'BRV' 'X6' 'Cruze' 'GLA' '6' 'NuvoSport' 'Scala' 'Jeep' 'Lodgy' 'Pulse'
 'Supro' 'Ingenio' 'Sonata' 'Renault' 'Kicks' 'Jetta' 'M-Class' 'Teana'
 'Yeti' 'Q3' 'Gurkha' 'Logan' 'A3' 'Dzire' 'Ikon' 'Fluence' 'Xenon' 'One'
 '7' 'S60' 'Lancer' 'X7' 'Premio' 'Fabia' 'Platinum' 'Captur' 'Gypsy'
 'Estate' 'Koleos' 'CLASSIC' 'Harrier' 'Multivan' 'Avventura' 'Laura'
 'Leyland' 'MUX' 'Astra' 'Tucson' 'Winger' 'Spacio' 'Venue' 'CrossPolo'
 'Marshal' 'Kodiaq' 'D-Max' 'X3' 'Land' 'X5' '309' 'Trailblazer' 'MU'
 'GLC' 'XC60' 'S90' 'S-Presso']
model
Swift       0.096737
Alto        0.057031
i20         0.043748
Wagon       0.035374
Innova      0.027144
              ...
MU          0.000144
GLC         0.000144
XC60        0.000144
S90         0.000144
S-Presso    0.000144
Name: proportion, Length: 207, dtype: float64

Column: edition
Cardinality: 1916
['Dzire VDI' '1.5 TDI Ambition' '2017-2020 EXi' ... '1.5 Revotorq XT'
 'Titanium Plus Diesel BSIV' '2.5 GX (Diesel) 8 Seater BS IV']
edition
Dzire VDI                         0.017037
VDI                               0.015305
800 LXI                           0.010973
LXi                               0.010540
LX                                0.010396
                                    ...
VX i-VTEC                         0.000144
2000 DSZ PW CL                    0.000144
Petrol Highline AT                0.000144
1.5 TDCi Titanium Plus BE BSIV    0.000144
1.5 Sports Edition MT             0.000144
Name: proportion, Length: 1916, dtype: float64

Column: owner
Cardinality: 5
['First' 'Second' 'Third' 'Fourth & Above' 'Test Drive Car']
owner
First             0.612475
Second            0.285013
Third             0.077390
Fourth & Above    0.024401
Test Drive Car    0.000722
Name: proportion, dtype: float64

Column: fuel
Cardinality: 4
['Diesel' 'Petrol' 'LPG' 'CNG']
fuel
Diesel    0.542160
Petrol    0.444268
CNG       0.008085
LPG       0.005487
Name: proportion, dtype: float64

Column: seller_type
Cardinality: 3
['Individual' 'Dealer' 'Trustmark Dealer']
seller_type
Individual          0.897776
Dealer              0.098325
Trustmark Dealer    0.003898
Name: proportion, dtype: float64

Column: transmission
Cardinality: 2
['Manual' 'Automatic']
transmission
Manual       0.91568
Automatic    0.08432
Name: proportion, dtype: float64

In [28]:
df = df.drop(columns=['name','model','edition'])    # Deletes columns('name','model' and 'edition') from dataset
df.head()

,company,year,owner,fuel,seller_type,transmission,km_driven,mileage_mpg,engine_cc,max_power_bhp,torque_nm,seats,selling_price
0,Maruti,2014,First,Diesel,Individual,Manual,145500,55.00,1248.0,74.00,190.000000,5.0,450000
1,Skoda,2014,Second,Diesel,Individual,Manual,120000,49.70,1498.0,103.52,250.000000,5.0,370000
2,Honda,2006,Third,Petrol,Individual,Manual,140000,41.60,1497.0,78.00,124.544455,5.0,158000
3,Hyundai,2010,First,Diesel,Individual,Manual,127000,54.06,1396.0,90.00,219.668960,5.0,225000
4,Maruti,2007,First,Petrol,Individual,Manual,120000,37.84,1298.0,88.20,112.776475,5.0,130000

In [29]:
df.duplicated().sum() #Checks for duplicated values

np.int64(19)

In [30]:
df = df.drop_duplicates()
df.head()

,company,year,owner,fuel,seller_type,transmission,km_driven,mileage_mpg,engine_cc,max_power_bhp,torque_nm,seats,selling_price
0,Maruti,2014,First,Diesel,Individual,Manual,145500,55.00,1248.0,74.00,190.000000,5.0,450000
1,Skoda,2014,Second,Diesel,Individual,Manual,120000,49.70,1498.0,103.52,250.000000,5.0,370000
2,Honda,2006,Third,Petrol,Individual,Manual,140000,41.60,1497.0,78.00,124.544455,5.0,158000
3,Hyundai,2010,First,Diesel,Individual,Manual,127000,54.06,1396.0,90.00,219.668960,5.0,225000
4,Maruti,2007,First,Petrol,Individual,Manual,120000,37.84,1298.0,88.20,112.776475,5.0,130000

In [31]:
df.duplicated().sum() #Checks for duplicated values again

np.int64(0)

In [32]:
X = df.drop(columns = 'selling_price')
y = df['selling_price'].copy()

print(X.shape,y.shape)

(6907, 12) (6907,)

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42) # Splitting data into train and test splits
print(X_train.shape,y_train.shape)
print(X_test.shape,y_test.shape)

(5525, 12) (5525,)
(1382, 12) (1382,)

In [34]:
X_train.select_dtypes(include='number') # fetches all the numeric columns

num_cols = X_train.select_dtypes(include='number').columns.tolist() # Fetches all numeric columns and adds them into a list

print(num_cols)

['year', 'km_driven', 'mileage_mpg', 'engine_cc', 'max_power_bhp', 'torque_nm', 'seats']

In [35]:
cat_cols = [col for col in X_train.columns if col not in num_cols]

cat_cols

print(cat_cols)

['company', 'owner', 'fuel', 'seller_type', 'transmission']

In [36]:
num_pipe = Pipeline(steps = [
    ('imputer',SimpleImputer(strategy='median')),
    ('scaler',StandardScaler())
])

cat_pipe = Pipeline(steps = [
    ('imputer',SimpleImputer(strategy='constant',fill_value='missing')),
    ('encoder',OneHotEncoder(handle_unknown='ignore',sparse_output=False))
])

preprocessor = ColumnTransformer(transformers = [
    ('num',num_pipe,num_cols),
    ('cat',cat_pipe,cat_cols)
])

regressor = RandomForestRegressor(
    n_estimators=10,
    max_depth=5,
    random_state=42
)

rf_model = Pipeline(
    steps=[
        ('pre',preprocessor),
        ('reg',regressor)
    ]
)

rf_model.fit(X_train,y_train)

Pipeline(steps=[('pre',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['year', 'km_driven',
                                                   'mileage_mpg', 'engine_cc',
                                                   'max_power_bhp', 'torque_nm',
                                                   'seats']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['company', 'owner', 'fuel',
                                                   'seller_type',
                                                   'transmission'])])),
                ('reg',
                 RandomForestRegressor(max_depth=5, n_estimators=10,
                                       random_state=42))])

In [38]:
import numpy as np

y_train_pred = rf_model.predict(X_train)
train_rmse = np.sqrt(mean_squared_error(y_train, y_train_pred))
print(f'Train RMSE: {train_rmse:,.3f}')

y_test_pred = rf_model.predict(X_test)
test_rmse = np.sqrt(mean_squared_error(y_test, y_test_pred))
print(f'Test RMSE: {test_rmse:,.3f}')

Train RMSE: 169,947.490
Test RMSE: 172,392.131